package mocks

import "github.com/stretchr/testify/mock"

import "github.com/jpatel531/team-finder/teams"

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: id
func (_m *Fetcher) Fetch(id int) (*teams.Team, error) {
	ret := _m.Called(id)

	var r0 *teams.Team
	if rf, ok := ret.Get(0).(func(int) *teams.Team); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*teams.Team)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
