package mocks

import "github.com/stretchr/testify/mock"

import "github.com/jpatel531/team-finder/teams"

// Targets is an autogenerated mock type for the Targets type
type Targets struct {
	mock.Mock
}

// Hit provides a mock function with given fields: team
func (_m *Targets) Hit(team *teams.Team) {
	_m.Called(team)
}

// IsComplete provides a mock function with given fields:
func (_m *Targets) IsComplete() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PlayersFound provides a mock function with given fields:
func (_m *Targets) PlayersFound() teams.Players {
	ret := _m.Called()

	var r0 teams.Players
	if rf, ok := ret.Get(0).(func() teams.Players); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(teams.Players)
		}
	}

	return r0
}

// TeamIsTargeted provides a mock function with given fields: teamName
func (_m *Targets) TeamIsTargeted(teamName string) bool {
	ret := _m.Called(teamName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(teamName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
